Update action-build.yml
Signed-off-by: Emirhan Durmuş <51929176+emirhandurmus@users.noreply.github.com>

diff --git a/.github/workflows/action-build.yml b/.github/workflows/action-build.yml
--- a/.github/workflows/action-build.yml
+++ b/.github/workflows/action-build.yml
@@ -1,216 +1,197 @@
+
 # yaml-language-server: $schema=https://json.schemastore.org/github-action.json
 
-name: CI
+# this action will require write permission to id-token
+name: Build shims
 
 on:
-  push:
-    branches:
-      - release/0.10.0
-    tags: [v*]
-  pull_request:
-    branches:
-      - test
-    paths-ignore:
-      - '*.md'
-      - 'docs/**'
-      - 'LICENSE'
-      - 'MAINTAINERS'
-      - 'NOTICE'
-      - 'art/**'
-
-env:
-  CARGO_TERM_COLOR: always
+  workflow_call:
+    inputs:
+      os:
+        required: true
+        type: string
+      runtime:
+        required: true
+        type: string
+      target:
+        required: false
+        type: string
+      slug:
+        required: true
+        type: string
+      arch:
+        required: false
+        type: string
+      sign:
+        default: false
+        type: boolean
+      binprefix:
+        default: containerd-shim-
+        type: string
+        required: false
 
 jobs:
-  dependency-review:
-    runs-on: ubuntu-latest
-    if: ${{ github.event_name == 'pull_request' }}
+  build-sign-upload:
+    permissions:
+      actions: write
+      checks: write
+      contents: write
+      deployments: write
+      id-token: write
+      issues: write
+      discussions: write
+      packages: write
+      pages: write
+      pull-requests: write
+      repository-projects: write
+      security-events: write
+      statuses: write
+    name: build for ${{ inputs.slug }}
+    runs-on: ${{ inputs.os }}
     steps:
+      - name: describe runner
+        run: |
+          echo "::notice::Running job with os: '${{ inputs.os }}', arch: '${{ inputs.arch }}', slug: '${{ inputs.slug }}', runtime: '${{ inputs.runtime }}', target: '${{ inputs.target }}'"
       - uses: actions/checkout@v4
-      - uses: actions/dependency-review-action@v4
+      - uses: ./.github/actions/setup-env
+      - uses: actions-rust-lang/setup-rust-toolchain@v1
+        env:
+          RUST_CACHE_KEY_OS: rust-cache-${{ inputs.os }}-${{ inputs.slug }}
+        with:
+          rustflags: '' #Disable.  By default this action sets environment variable is set to -D warnings.  We manage this in the Makefile
+      - name: Setup cross-rs
+        if: runner.os == 'Linux'
+        run: ./scripts/setup-cross.sh ${{ inputs.target }}
+      - name: Setup build profile
+        shell: bash
+        run: echo "OPT_PROFILE=release" >> ${GITHUB_ENV}
+      - name: Build
+        run: make build-${{ inputs.runtime }}
+      - name: Check if crate is ready to publish
+        if: ${{ inputs.runtime == 'common' }}
+        shell: bash
+        run: make publish-check
+      - name: Run tests
+        timeout-minutes: 5
+        run: |
+          make test-${{ inputs.runtime }}
+        if: ${{ inputs.arch == 'x86_64' }}
+      - name: Install binaries
+        if: ${{ inputs.runtime != 'common' }}
+        shell: bash
+        run: |  
+          make dist-${{ inputs.runtime }}
+      - name: Run stress tests
+        if: ${{ inputs.runtime != 'common' && inputs.binprefix == 'containerd-shim-' && inputs.arch == 'x86_64' && runner.os == 'Linux' }}
+        timeout-minutes: 5
+        shell: bash
+        run: |
+          set -euox pipefail
+          sudo ctr images pull ghcr.io/containerd/runwasi/wasi-demo-app:latest
+          make test/stress-${{ inputs.runtime }}
+      - name: Run stress tests with containerd
+        if: ${{ inputs.runtime != 'common' && inputs.binprefix == 'containerd-shim-' && inputs.arch == 'x86_64' && runner.os == 'Linux' }}
+        timeout-minutes: 5
+        shell: bash
+        run: |
+          set -euox pipefail
+          sudo ctr images pull ghcr.io/containerd/runwasi/wasi-demo-app:latest
+          make test/stress-c8d-${{ inputs.runtime }}
+      - name: Sign the binary
+        if: ${{ inputs.runtime != 'common' && inputs.slug != 'windows' && inputs.sign }}
+        uses: ./.github/actions/sign
+        with:
+          runtime: ${{ inputs.runtime }}
+      - name: 'Get Previous tag'
+        id: previoustag
+        uses: "WyriHaximus/github-action-get-previous-tag@v1"
+        with:
+          fallback: 0.0.0
+      - name: Set image tag
+        shell: bash
+        id: tags
+        run: |
+          if [[ ${{ github.ref_name }} =~ ^v.* ]] ; then
+            version=$(echo "${{ github.ref_name }}" | sed 's/^v//')
+            echo "VERSION=$version" >> "${GITHUB_OUTPUT}"
+          else
+            version=$(echo "${{ steps.previoustag.outputs.tag }}-${{ github.run_number }}" | sed 's/^v//')-dev
+            echo "VERSION=$version" >> "${GITHUB_OUTPUT}"
+          fi
+      - name: Get image tag
+        run: |
+          echo ${{ steps.tags.outputs.VERSION }}
+      - name: Set up Ruby 3.1.4
+        uses: ruby/setup-ruby@v1
+        with:
+          ruby-version: 3.1.4
+      - run: |
+          gem install --no-document fpm
+          fpm -h
+      - name: Package artifacts
+        id: package
+        if: ${{ inputs.runtime != 'common' && inputs.slug != 'windows' }}
+        shell: bash
+        run: |
+          # Check if there's any files to archive as tar fails otherwise
+          if stat dist/bin/* >/dev/null 2>&1; then
+            tar -czf dist/${{ inputs.binprefix }}${{ inputs.runtime }}-${{ inputs.slug }}.tar.gz -C dist/bin .
+          else
+            tar -czf dist/${{ inputs.binprefix }}${{ inputs.runtime }}-${{ inputs.slug }}.tar.gz -T /dev/null
+          fi
 
-  check:
-    name: ${{ matrix.runtime }}
-    strategy:
-      matrix:
-        os: ["ubuntu-latest", "windows-latest"]
-        runtime: ["common", "wasmedge", "wasmtime", "wasmer", "wamr"]
-    uses: ./.github/workflows/action-check.yml
-    with:
-      os: ${{ matrix.os }}
-      runtime: ${{ matrix.runtime }}
-  
-  test-image:
-    name: ${{ matrix.runtime }}
-    strategy:
-      matrix:
-        runtime: ["common"] # not required, but groups jobs
-    uses: ./.github/workflows/action-test-image.yml
-
-  test-image-oci:
-    name: ${{ matrix.runtime }}
-    strategy:
-      matrix:
-        runtime: ["common"] # not required, but groups jobs
-    uses: ./.github/workflows/action-test-image.yml
-    with:
-      image: img-oci
-
-  build-ubuntu:
-    name: ${{ matrix.runtime }}
-    permissions:
-      actions: write
-      checks: write
-      contents: write
-      deployments: write
-      id-token: write
-      issues: write
-      discussions: write
-      packages: write
-      pages: write
-      pull-requests: write
-      repository-projects: write
-      security-events: write
-      statuses: write
-    strategy:
-      matrix:
-        os: ["ubuntu-22.04"]
-        runtime: ["common", "wasmtime", "wasmedge", "wasmer", "wamr"]
-        # libc: ["musl", "gnu"]
-        libc: ["gnu"]
-        arch: ["x86_64", "aarch64"]
-    uses: ./.github/workflows/action-build.yml
-    with:
-      os: ${{ matrix.os }}
-      runtime: ${{ matrix.runtime }}
-      target: "${{ matrix.arch }}-unknown-linux-${{ matrix.libc }}"
-      slug: "${{ matrix.arch }}-linux-${{ matrix.libc }}"
-      arch: ${{ matrix.arch }}
-
-  build-windows:
-    name: ${{ matrix.runtime }}
-    permissions:
-      actions: write
-      checks: write
-      contents: write
-      deployments: write
-      id-token: write
-      issues: write
-      discussions: write
-      packages: write
-      pages: write
-      pull-requests: write
-      repository-projects: write
-      security-events: write
-      statuses: write
-    strategy:
-      matrix:
-        os: ["windows-latest"]
-        runtime: ["common", "wasmtime", "wasmedge", "wasmer"]
-    uses: ./.github/workflows/action-build.yml
-    with:
-      os: ${{ matrix.os }}
-      runtime: ${{ matrix.runtime }}
-      slug: "windows"
-  
-  build-oci-tar-builder:
-    name: oci-tar-builder-${{ matrix.os }}
-    strategy:
-      matrix:
-        os: ["ubuntu-22.04"]
-        arch: ["x86_64", "aarch64"]
-    uses: ./.github/workflows/action-build.yml
-    with:
-      os: ${{ matrix.os }}
-      runtime: "oci-tar-builder"
-      target: "${{ matrix.arch }}-unknown-linux-gnu"
-      slug: "${{ matrix.arch }}-linux-gnu"
-      arch: ${{ matrix.arch }}
-      sign: false
-      binprefix: ""
-
-  smoke-tests:
-    name: ${{ matrix.runtime }}
-    needs: [build-ubuntu, test-image]
-    strategy:
-      matrix:
-        # 20.04 uses cgroupv1, 22.04 uses cgroupv2
-        os: ["ubuntu-20.04", "ubuntu-22.04"]
-        runtime: ["wasmtime", "wasmedge", "wasmer", "wamr"]
-    uses: ./.github/workflows/action-test-smoke.yml
-    with:
-      os: ${{ matrix.os }}
-      runtime: ${{ matrix.runtime }}
-
-  e2e-kind:
-    name: ${{ matrix.runtime }}
-    needs: [build-ubuntu, test-image]
-    strategy:
-      fail-fast: false
-      matrix:
-        # 20.04 uses cgroupv1, 22.04 uses cgroupv2
-        os: ["ubuntu-20.04", "ubuntu-22.04"]
-        runtime: ["wasmtime", "wasmedge", "wasmer", "wamr"]
-    uses: ./.github/workflows/action-test-kind.yml
-    with:
-      os: ${{ matrix.os }}
-      runtime: ${{ matrix.runtime }}
-      test-command: make test/k8s-${{ matrix.runtime }}
-
-  e2e-kind-oci:
-    name: ${{ matrix.runtime }}
-    needs: [build-ubuntu, test-image-oci]
-    strategy:
-      matrix:
-        os: ["ubuntu-22.04"]
-        runtime: ["wasmtime", "wasmedge", "wasmer", "wamr"]
-    uses: ./.github/workflows/action-test-kind.yml
-    with:
-      os: ${{ matrix.os }}
-      runtime: ${{ matrix.runtime }}
-      image: img-oci
-      test-command: make test/k8s-oci-${{ matrix.runtime }}
-
-  e2e-k3s:
-    name: ${{ matrix.runtime }}
-    needs: [build-ubuntu, test-image]
-    strategy:
-      fail-fast: false
-      matrix:
-        os: ["ubuntu-20.04", "ubuntu-22.04"]
-        runtime: ["wasmtime", "wasmedge", "wasmer", "wamr"]
-    uses: ./.github/workflows/action-test-k3s.yml
-    with:
-      os: ${{ matrix.os }}
-      runtime: ${{ matrix.runtime }}
-
-  docs:
-    name: docs
-    runs-on: ubuntu-latest
-    steps:
-    - uses: actions/checkout@v4
-    - uses: ./.github/actions/setup-env
-    - uses: actions-rust-lang/setup-rust-toolchain@v1
-    - uses: Swatinem/rust-cache@v2
-    - name: Check documentation
-      run: make test-doc
-    - name: Generate documentation
-      run: make generate-doc
-
-  deps:
-    name: unused dependencies
-    runs-on: ubuntu-latest
-    steps:
-    - uses: actions/checkout@v4
-    - uses: actions-rust-lang/setup-rust-toolchain@v1
-    - uses: Swatinem/rust-cache@v2
-    - name: Check unused dependencies
-      uses: bnjbvr/cargo-machete@v0.8.0
-
-  spelling:
-    name: spell check with typos
-    runs-on: ubuntu-latest
-    steps:
-    - uses: actions/checkout@v4
-    - name: Spell Check Repo
-      uses: crate-ci/typos@master
+          # Map inputs.slug to proper architecture for fpm
+          if [[ "${{ inputs.slug }}" == "x86_64-linux-gnu" || "${{ inputs.slug }}" == "x86_64-linux-musl" ]]; then
+              arch="amd64"
+          elif [[ "${{ inputs.slug }}" == "aarch64-linux-gnu" || "${{ inputs.slug }}" == "aarch64-linux-musl" ]]; then
+              arch="arm64"
+          else
+              echo "Unsupported architecture slug: ${{ inputs.slug }}"
+              exit 1
+          fi
+          echo "arch=$arch" >> "${GITHUB_OUTPUT}"
+          # Ensure the binary exists
+          binary_path="/home/runner/work/runwasi/runwasi/dist/bin/containerd-shim-${{ inputs.runtime }}-v1"
+          if [[ -f $binary_path ]]; then
+              cd /home/runner/work/runwasi/runwasi/dist/bin/
+              ls -la /home/runner/work/runwasi/runwasi/dist/bin/
+              # Map slug for DEB explicitly
+              deb_slug=${{ inputs.slug }}
+              if [[ "$deb_slug" == "x86_64-linux-gnu" ]]; then
+                  deb_slug="x86-64-linux-gnu"
+              fi
+              echo "deb_slug=$deb_slug" >> "${GITHUB_OUTPUT}"
+              # Create a .deb package
+              fpm -s dir -t deb --name containerd-shim-${{ inputs.runtime }}-v1-${{ inputs.slug }} --version ${{ steps.tags.outputs.VERSION }} --architecture $arch --depends 'docker-ce > 26.0.0' ./containerd-shim-${{ inputs.runtime }}-v1=/usr/local/bin/containerd-shim-${{ inputs.runtime }}-v1
+              # Map architecture for RPM explicitly
+              rpm_arch=$arch
+              if [[ "$arch" == "arm64" ]]; then
+                  rpm_arch="aarch64" #
+              elif [[ "$arch" == "amd64" ]]; then
+                  rpm_arch="x86_64"
+              fi
+              echo "rpm_arch=$rpm_arch" >> "${GITHUB_OUTPUT}"
+              # Create an .rpm package
+              fpm -s dir -t rpm --name containerd-shim-${{ inputs.runtime }}-v1-${{ inputs.slug }} --version ${{ steps.tags.outputs.VERSION }} --architecture $rpm_arch --rpm-os 'linux' --depends 'docker-ce > 26.0.0' ./containerd-shim-${{ inputs.runtime }}-v1=/usr/local/bin/containerd-shim-${{ inputs.runtime }}-v1
+              # Move generated packages
+              mkdir -p /home/runner/work/runwasi/runwasi/dist/packages
+              mv *.deb *.rpm /home/runner/work/runwasi/runwasi/dist/packages
+              ls -la /home/runner/work/runwasi/runwasi/dist/bin/
+              ls -la /home/runner/work/runwasi/runwasi/dist/packages/
+          else
+              echo "No binaries found to package"
+              exit 1
+          fi
+      - name: Upload artifacts
+        if: ${{ inputs.runtime != 'common' && inputs.slug != 'windows' }}
+        uses: actions/upload-artifact@master
+        with:
+          name: ${{ inputs.binprefix }}${{ inputs.runtime }}-${{ inputs.slug }}
+          path: dist/${{ inputs.binprefix }}${{ inputs.runtime }}-${{ inputs.slug }}.tar.gz
+      - name: Release
+        uses: softprops/action-gh-release@v1
+        if: ${{ inputs.runtime != 'common' && inputs.slug != 'windows' && startsWith(github.ref, 'refs/tags/')}}
+        with:
+          files: |
+            /home/runner/work/runwasi/runwasi/dist/packages/containerd-shim-${{ inputs.runtime }}-v1-${{ steps.package.outputs.deb_slug }}_${{ steps.tags.outputs.VERSION }}_${{ steps.package.outputs.arch }}.deb
+            /home/runner/work/runwasi/runwasi/dist/packages/containerd-shim-${{ inputs.runtime }}-v1-${{ inputs.slug }}-${{ steps.tags.outputs.VERSION }}-1.${{ steps.package.outputs.rpm_arch }}.rpm
